import React from 'react';
import { Award, HeartHandshake, TrendingUp, Users } from 'lucide-react';

const headlineStats = [
  {
    icon: Users,
    number: '2,500+',
    label: 'Active founders',
    detail: 'Women building momentum through URAAN.',
  },
  {
    icon: TrendingUp,
    number: 'PKR 5Cr+',
    label: 'Community revenue',
    detail: 'Generated by members using our launch plans.',
  },
  {
    icon: Award,
    number: '150+',
    label: 'Business launches',
    detail: 'Validated businesses moved from idea to market.',
  },
  {
    icon: HeartHandshake,
    number: '95%',
    label: 'Satisfaction score',
    detail: 'Founders rate URAAN as high impact.',
  },
];

const growthMilestones = [
  { name: 'Validation sprint', value: 'Week 1', width: 'w-1/3' },
  { name: 'First offer live', value: 'Week 3', width: 'w-2/3' },
  { name: 'Revenue ready', value: 'Week 6', width: 'w-full' },
];

const StatsSection: React.FC = () => {
  return (
    <section className="relative px-4 py-20 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-7xl">
        <div className="mb-14 text-center">
          <p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">Real traction</p>
          <h2 className="font-display mt-4 text-4xl leading-tight text-text md:text-5xl">
            Built for measurable outcomes
          </h2>
          <p className="mx-auto mt-4 max-w-3xl text-lg leading-relaxed text-text/70">
            Premium positioning only matters if it converts to real progress. These numbers show how founders use URAAN to launch with clarity and scale with intent.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-5 md:grid-cols-2 lg:grid-cols-4">
          {headlineStats.map((stat, index) => (
            <article
              key={stat.label}
              className="premium-card animate-reveal-up rounded-3xl p-6"
              style={{ animationDelay: `${index * 110}ms` }}
            >
              <div className="mb-5 inline-flex h-12 w-12 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-accent2 text-baby-powder shadow-[0_10px_25px_-12px_rgba(138,31,74,0.9)]">
                <stat.icon size={22} />
              </div>
              <p className="text-3xl font-bold text-text">{stat.number}</p>
              <p className="mt-2 text-base font-semibold text-text">{stat.label}</p>
              <p className="mt-2 text-sm leading-relaxed text-text/70">{stat.detail}</p>
            </article>
          ))}
        </div>

        <div className="mt-10 rounded-3xl border border-primary/15 bg-baby-powder/70 p-7 backdrop-blur-xl">
          <div className="mb-6 flex flex-wrap items-center justify-between gap-3">
            <h3 className="font-display text-2xl text-text">Founder velocity map</h3>
            <span className="rounded-full border border-primary/20 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.12em] text-primary">
              Typical first 6 weeks
            </span>
          </div>
          <div className="space-y-4">
            {growthMilestones.map((milestone) => (
              <div key={milestone.name}>
                <div className="mb-2 flex items-center justify-between text-sm">
                  <p className="font-semibold text-text">{milestone.name}</p>
                  <p className="text-text/60">{milestone.value}</p>
                </div>
                <div className="h-2 rounded-full bg-secondary/20">
                  <div
                    className={`h-full ${milestone.width} rounded-full bg-gradient-to-r from-primary to-accent2`}
                  />
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
